ALTER TABLE "Task" ADD COLUMN "labels" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Task" ADD COLUMN "comments" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Task" ADD COLUMN "checklist" JSONB NOT NULL DEFAULT '[]';
